server:
  port: 9080
  servlet:
    context-path: /api/burn
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: coding-fist-burnig-house-austinAndJsonKim-is-the-best-team-shitttttttttt
#토큰의 암호화 복호화를 위한 secret key로서 이후 HS256 알고리즘을 사용하기 위해, 256비트보다 커야한다.
#고로 알파벳은 한단어 당 8bit 이므로 32글자 이상이면 된다.
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    user:
      name: austin
      password: austin
  mail:
    host: smtp.gmail.com
    port: 587
    username: dpdlfgkgustn@gmail.com
    password: t1183023
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true





  datasource:
    url: jdbc:mariadb://localhost:3306/burning_house_auth?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: austin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true



app:
  filePath: /var/app/poc_dev/upload
#  filePath: /var/app/poc/upload


